# Generated by Django 5.0.1 on 2024-02-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets4uweb', '0003_alter_pet_age_alter_pet_location_alter_user_email_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_id',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.IntegerField(null=True),
        ),
    ]
