# Generated by Django 5.0.1 on 2024-02-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets4uweb', '0004_alter_user_email_id_alter_user_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_id',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
