# Generated by Django 5.0.1 on 2024-02-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets4uweb', '0006_alter_user_email_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_id',
            field=models.EmailField(blank=True, max_length=255),
        ),
    ]
